ALTER TABLE users
  ADD COLUMN IF NOT EXISTS kelurahan_id INT NULL AFTER id,
  MODIFY COLUMN name TEXT NOT NULL,
  MODIFY COLUMN address TEXT NULL,
  MODIFY COLUMN phone TEXT NULL;

ALTER TABLE chat_conversations
  ADD COLUMN IF NOT EXISTS kelurahan_id INT NULL AFTER id,
  MODIFY COLUMN subject TEXT NULL;

ALTER TABLE citizen_aspirations
  ADD COLUMN IF NOT EXISTS kelurahan_id INT NULL AFTER id,
  MODIFY COLUMN name TEXT NOT NULL,
  MODIFY COLUMN short_title TEXT NOT NULL;
