ALTER TABLE citizen_aspirations
  ADD COLUMN IF NOT EXISTS name TEXT NULL,
  ADD COLUMN IF NOT EXISTS address TEXT NULL,
  ADD COLUMN IF NOT EXISTS category VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS short_title TEXT NULL,
  ADD COLUMN IF NOT EXISTS description TEXT NULL;
